name: cntk-py35
channels:
- defaults
# For imageio, opencv (and pillow):
- conda-forge
dependencies:
- h5py=2.6.0=np111py35_2
- imageio=2.2.0=py35_0
- pyqt=5.6.0=py35ha878b3d_6
- jupyter=1.0.0=py35_3
- matplotlib=2.0.0=np111py35_0
- pandas=0.19.1=np111py35_0
- pandas-datareader=0.2.1=py35_0
- pandoc=1.19.2.1
- pillow=3.2.0=py35_1
- pip=8.1.2=py35_0
- python=3.5.2=0
- pyyaml=3.12=py35_0
- scikit-image=0.12.3=np111py35_1
- scikit-learn=0.18.1=np111py35_0
- scipy=0.18.1=np111py35_0
- seaborn=0.7.1=py35_0
- setuptools=27.2.0=py35_1
- six=1.10.0=py35_0
- wheel=0.29.0=py35_0
- opencv=3.1.0=np111py35_1
- dlib=19.0=np111py35_200
- pip:
  - gym==0.5.2
  - keras==2.0.6
  - pydot-ng==1.0.0
  - pygame==1.9.3
  - pytest==3.0.3
  - sphinx-rtd-theme==0.2.4
  - sphinx==1.5.4
  - nbsphinx==0.2.14
  - twine==1.8.1
  - gym==0.5.2
  - pydot-ng==1.0.0
  - easydict==1.6.0
  - protobuf==3.6.0
  - numpy==1.15.0
  - typing==3.6.6
  - typing-extensions==3.6.5
  - onnx==1.2.2
