name: cntk-py35
channels: !!python/tuple
- defaults
dependencies:
- h5py=2.6.0=np111py35_2
- jupyter=1.0.0=py35_3
- matplotlib=1.5.3=np111py35_0
- numpy=1.11.2=py35_0
- pandas=0.19.1=np111py35_0
- pandas-datareader=0.2.1=py35_0
- pillow=3.4.2=py35_0
- pip=8.1.2=py35_0
- python=3.5.2=0
- pyyaml=3.12=py35_0
- scipy=0.18.1=np111py35_0
- seaborn=0.7.1=py35_0
- setuptools=27.2.0=py35_0
- six=1.10.0=py35_0
- wheel=0.29.0=py35_0
- pip:
  - pytest==3.0.3
  - sphinx==1.4.8
  - sphinx-rtd-theme==0.1.9
  - twine==1.8.1
  - gym==0.5.2
